name: rookies_jeans
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  cached_network_image: ^3.4.1
  video_player: ^2.11.1
  snap_scroll_physics: ^0.0.1+3
  go_router: ^17.3.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  fluttertoast: ^9.1.0
  webview_flutter: ^4.14.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/          # root assets (images, video, etc.)
    - assets/fonts/    # ← required so Flutter finds the .ttf files

  fonts:
  - family: BebasNene
    fonts:
      - asset: assets/fonts/BebasNeue-Regular.ttf
        weight: 500

  - family: SplineSansMono
    fonts:
      - asset: assets/fonts/SplineSansMono-VariableFont_wght.ttf 
        weight: 400

  - family: LibreFranklin
    fonts:
      - asset: assets/fonts/LibreFranklin-VariableFont_wght.ttf 
        weight: 500
  - family: AlteHaasGroteskRegular
    fonts:
      - asset: assets/fonts/AlteHaasGroteskRegular.ttf

  - family: AlteHaasGroteskBold
    fonts:
      - asset: assets/fonts/AlteHaasGroteskBold.ttf
        weight: 700